//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSCRUD.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int ID { get; set; }
        public string CNombre { get; set; }
        public string DNombre { get; set; }
        public string DApellidos { get; set; }
        public int NumHoras { get; set; }
        public int NumAlumnos { get; set; }
    }
}
